export const BLOCK_ASSET_KEYS = Object.freeze({
    BACKGROUND: 'BLOCK_ASSET_KEYS.BACKGROUND',
    ICON: 'BLOCK_ASSET_KEYS.ICON',
});

export const UNIT_ASSET_KEYS = Object.freeze({
    BACKGROUND: 'UNIT_ASSET_KEYS.BACKGROUND',
});

export const PANEL_ASSET_KEYS = Object.freeze({
    BACKGROUND: 'PANEL_ASSET_KEYS.BACKGROUND',
    ICON: 'PANEL_ASSET_KEYS.ICON',
    FONT: 'PANEL_ASSET_KEYS.FONT',
});

export const FONT_ASSET_KEYS = Object.freeze({
    POINT: 'FONT_ASSET_KEYS.POINT',
});
